### PR TITLE
Attenuator

### PR DESCRIPTION
**Pull request by agastya1208**
Attenuator() is a simple element that attenuates the power of optical signals state.

- Added Attenuator() element by sub-classing the Amplifier element in node.py file
- Changed the span parsing functions in dataplane.py to handle classes instead of hard-coding Physical Amplifiers.
- Added attenuator_test.py file as test to check that the implementation is correct, and signal is being attenuated
- Added pdf file for Installation walk through of mininet-optical for ARM based MAC computers.

### CODE REVIEW

**Comment by lantz** [comment]
1. The documentation change seems unrelated. Could you create a separate PR for it? Also it should be added to the sphinx documentation. Any text should be in .md (markdown) format and any graphics should be in (optimized, compact!) .svg format.
2. Could you rebase against the current attenuator branch?

**Comment by agastya1208** [comment]
Hi Bob, I have removed the documentation for now. I will write it in proper format and create a PR later. For now, I have rebased the code based on current attenuator branch, and solved any merge conflicts that were occurring.

**Comment by lantz** [comment]
@agastya1208 I realize the debugging prints are extraneous, but is there any reason your code won't work with my dataplane changes?

**Comment by agastya1208** [comment]
@lantz I am getting an error with the existing dataplane.py code in current attenuator branch. It's probably just with parsing the span tuples. I will resolve this shortly and try to make my code to work with your dataplane changes; and then do the code commit

**Comment by agastya1208** [comment]
@lantz I saw that you edited the component() function in OpticalLink class and changed the `if prefix and args:` to `if prefix and not getattr(cls, 'anonymous', False)`. Can you help me understand this bit? 
That's the only bit in your dataplane.py that's not working with my code. If I change it back to "if prefix and args:" it works!

**Comment by lantz** [comment]
`component()` was expecting `name` to be passed as a positional parameter, but you were passing it as a named parameter. It should work now.

Could you make sure that your test script accepts a `test` argument which causes it to run in test mode and verify that the signal power attenuation is operating as expected?

**Comment by agastya1208** [comment]
Hi @lantz, thanks for explaining the `component()` bit, it is very helpful. I have rebased with the current branch, and have added tests for both emulation and simulation. Both the tests have attenuators with loss value of 1dB, and the tests check that the power levels are dropping after adding the component. Please review and let me know for additional changes

**Review by lantz — CHANGES_REQUESTED** [review]
This looks good - can you add a check in `attenuator_test.py` to make sure that:
1. The actual attenuation is working as expected.
2. Going through single or multiple attenuators works as expected?

**Comment by agastya1208** [comment]
@lantz I have added the simulation test to check for both signal power and noise power. Also added test to check whether signals are propagating correctly through multiple attenuators. 
Apologies for the messy commit history, it's my first time collaborating with multiple people on github so I'm still learning. Thank you for pointing it out, I will take care of this from now on. I have squashed the commits and rebased it on the current attenuator branch. Please take a look and let me know if any further changes are required.

**Comment by lantz** [comment]
Oh my bad haha, I was thinking you were committing to `attenuator` rather than submitting a PR against it.

I've fixed `attenuator` itself. I left the propagation fix as its own commit for now.

**Comment by lantz** [comment]
@agastya1208 Is there a numerical validation test in `tests/attenuator_test.py` that causes the test to exit with a nonzero status if it fails?

**Comment by agastya1208** [comment]
I have added assertion tests which numerically validate the signal and noise power loss with the attenuation values. I didn't see such statement in other files, that's why I was not sure if I should add it

**Comment by agastya1208** [comment]
This PR was merged with another PR#139 and was pushed to `master`

**Pull request closed without merging**
