### PR TITLE
Added Attenuator component and corresponding tests

### PR DESCRIPTION
**Pull request by lantz**
Attenuator() is a simple element that attenuates the power of optical
signals state.

- Added Attenuator() element by sub-classing the Amplifier element in
  node.py file

- Added attenuator_test.py file as test to check that the implementation
  is correct, and signal is being attenuated

### CODE REVIEW

**Comment by lantz** [comment]
@agastya1208 I created a PR against `master` with your changes. If it looks OK to you, please feel free merge it and close #128.

**Comment by lantz** [comment]
@agastya1208  Note I removed my LBO for now although it also works fine and I also have a test for it.

**Comment by lantz** [comment]
@agastya1208  What did you think of my `LBO` version btw? It was something like:
```class LBO(Span):
    "A simple attenuator/Line Break Out"
    def __init__(self, loss=0):
        "loss: loss expressed in (non-negative) dB"
        super().__init__()
        assert loss >= 0, "LBO: loss should be non-negative"
        self.loss = loss
    def output_nonlinear_noise(self): pass
    def srs_effect_model(): pass
    def __repr__(self): return f'<LBO{self.span_id} -{self.loss}dB>'
    def attenuation(self): return db_to_abs(self.loss)
```

**Comment by agastya1208** [comment]
Thank you @lantz , I will merge this PR and close #128. The LBO version based on Spans also looks good, we could also include your version. But I thought that Amplifier based attenuators can later be incorporated into ROADMs and other components more easily, to simulate built-in attenuators, from a future development perspective

**Review by agastya1208 — APPROVED** [review]

**Pull request merged**
