### PR TITLE
Add SIGCOMM 2022 COSMOS tutorial files

### PR DESCRIPTION
**Pull request by lantz**
This is a placeholder PR for the COSMOS/SIGCOMM22 tutorial which we may wish to merge once it is finished.

### CODE REVIEW

**Comment by lantz** [comment]
@agastya1208  Why is it necessary to pass both `channels` and `power`?

**Comment by agastya1208** [comment]
@lantz Did you mean for the comb source? The COMB source in hardware is passing signals only for 30 channels, namely [[10-19],[40-49],[80-89]]. Another way could be to pass all channels powers, with power=0.0dB for the channels which are not active

**Comment by lantz** [comment]
I was thinking of passing a `channels` dict which contains `{channel:power}` for each channel you want to use.

**Comment by agastya1208** [comment]
Ah my bad. You're right, just need to pass the dictionary. I will modify that
Also, I just pushed an updated code with correct server names to match the hardware; and added an method to get the power levels across all monitors in a text. I think it got deleted because of the force-push. I will push it again with the updated Comb source

**Comment by lantz** [comment]
Oh really? That's very bad timing since there was only like a 1s window.

**Comment by lantz** [comment]
I still don't see the correct server names etc. so it must have been stepped on somehow - sorry about that! If you could add it again I'm done with hitting `update` for now.

**Comment by agastya1208** [comment]
Haha yes that's a bit of coincidence. But I will update with the latest branch and push it again

**Comment by lantz** [comment]
Are you going to rename the ROADMs and ToR switches (and possibly variable names) as well?

**Comment by agastya1208** [comment]
Hi @lantz, 
1. I have renamed the ROADM and ToR switches according to hardware (but removed the dash(-) to follow the 16-bit interface name limit in Linux). If i get the time later, I will add the dashes(-), and pass individual interface names in wdmLinks 
2. Have added the config script
3. Have updated the comments. Will add the link to wiki page when we are done with it.
4. Emmanuel has created the WDG gain static functions in edfa_params.py, but I am waiting on his response to see how o we use those values. Till then I have left the WDG functions for boost and amplifiers as is

**Comment by lantz** [comment]
I think you might have had the right idea changing the dashes in the node names to underscores to work better with python and the mininet CLI.

**Comment by lantz** [comment]
there seems to be some naming inconsistency between the ascii art topology diagram and the code

**Comment by lantz** [comment]
@juraul1 @agastya1208 I flattened this and merged `CombSource` upstream. If this looks OK to you, I think we can merge it.

**Review by juraul1 — APPROVED** [review]

**Review by agastya1208 — APPROVED** [review]

**Pull request merged**
