### PR TITLE
SRS test

### PR DESCRIPTION
**Pull request by manny118**

### CODE REVIEW

**Comment by lantz** [comment]
How is this related to #123?

**Comment by manny118** [comment]
This is a test for the "srs_effect_model()" which we discussed some time ago. Yes, the tests fail since it needs the SRS flag in the link.py class to be on.

**Comment by manny118** [comment]
This has been replaced with [request](https://github.com/Mininet-Optical/mininet-optical/pull/132#issue-1330511090).

**Comment by lantz** [comment]
@manny118  Remember that you don't need to make a new PR unless you want to. You can update this one by pushing to it (with `--force` if necessary.) Usually this is easier than creating a new PR and it also makes it easier to keep track of.

**Pull request closed without merging**
